[activitypub]
    inbox = "https://vrutkovs.eu/activitypub/blog/inbox"
    publickeypem = """
    -----BEGIN CERTIFICATE-----
    MIIFQjCCBCqgAwIBAgISA4c3aiuqmFyZXq68ZbOxJ76gMA0GCSqGSIb3DQEBCwUA
    MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
    EwJSMzAeFw0yMTAxMTkwODQyNDVaFw0yMTA0MTkwODQyNDVaMBYxFDASBgNVBAMT
    C3ZydXRrb3ZzLmV1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyTzU
    DRiSlnYP7r5738T/lobi0l9Bwv5tNGP+vpdtUvr3/258PQEEcYMVQmbIMsOfW3Ya
    xAqowhR1WRdB5OYmn86s0tDYLM/BRHxHbexzn7M1g7TWXCEe9b4MkUgoL7QO1gZB
    VI9Ymvpgeh8ARYfnVVsTJe+e+SvJwmJ76TDlBm9NYB1rRjASGNWjDAlwx7ss0eLE
    rc3D0Hoq41qLBdnggvcOwJT4V45hrnlaTo/SWvZFbtVIE9LTijMRoLmalDwXiD7w
    A6scVePZuVNDf5uBRwNPv0MUVPf6/NSA0MVsmn2GJFGcG7zwdC5Nx2iohb7RU+0N
    VYs0IU/c17c0m8dI1QIDAQABo4ICbDCCAmgwDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQW
    BBTDiV4Hh6LouiuAvOLPhSZnDp1oFTAfBgNVHSMEGDAWgBQULrMXt1hWy65QCUDm
    H6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYBBQUHMAGGFWh0dHA6Ly9yMy5v
    LmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3IzLmkubGVuY3Iub3JnLzA9
    BgNVHREENjA0ghYqLmFwcHMub2tkLnZydXRrb3ZzLmV1gg0qLnZydXRrb3ZzLmV1
    ggt2cnV0a292cy5ldTBMBgNVHSAERTBDMAgGBmeBDAECATA3BgsrBgEEAYLfEwEB
    ATAoMCYGCCsGAQUFBwIBFhpodHRwOi8vY3BzLmxldHNlbmNyeXB0Lm9yZzCCAQMG
    CisGAQQB1nkCBAIEgfQEgfEA7wB1APZclC/RdzAiFFQYCDCUVo7jTRMZM7/fDC8g
    C8xO8WTjAAABdxoGcUYAAAQDAEYwRAIgJwKvOQua5AcSoE9mmREMiryWqyQbL0BH
    nXT9bAGmGggCIBlGzG8NSNDTc+57JUaRrTIvH+hQmim0eWIiW6vY12yBAHYAb1N2
    rDHwMRnYmQCkURX/dxUcEdkCwQApBo2yCJo32RMAAAF3GgZydQAABAMARzBFAiAe
    Dbvm+SgpyL7OpZGzyU7157aeK2lTrPLp1jPnWFJPDwIhAJyEYroZNUdlYhw9DOIr
    AwK3A0SAnqZBMPA74j5jeiitMA0GCSqGSIb3DQEBCwUAA4IBAQAaHg0yu1lj46Is
    zCtmIVEz9DTFxs+eK3p5VjytOs7DUzVV5qKIR2u2mtt2762CYZZ4iiS/w5tAUcBZ
    1/ZbhCBwEyQ12inL20ZI1KzqYlrL+rImv/khi6Skmcr1fY+FSc15iKY1pCtgk88l
    PeWRgS+SRG2klkHd6aimUQ1k43akzcRO6KRGz+dFP5clvMu60qQZo7tFlSSbSMBd
    +VvqxDKK3FUOVs3dDH6rX4WoIhxPO/K9JzC36Rw8e1ZVF/cLqy4eI/PQ+JwWMHbk
    ER9sr8ujf+C8leers6OGkJPIWLNxB8mcxTwQEqRYAtR+Wry8k/mmpBorXNzAjeRT
    KiJJ/JgR
    -----END CERTIFICATE-----
    """
