name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix build .#containerImage
      - name: login to quay
        run: |
          docker login -u vrutkovs -p $DOCKER_PASSWORD quay.io
          skopeo --insecure-policy copy docker-archive:./result docker://quay.io/vrutkovs/blog:latest
        env:
          DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        if: github.event_name == 'push'
