name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: vrutkovs/action-s2i@master
      with:
        path: .
        base: quay.io/vrutkovs/sti-hugo:v0.119
        image: blog:src
    - uses: vrutkovs/action-bin-container@master
      with:
        source_image: blog:src
        source_path: /opt/app-root/src/public
        binary_base: quay.io/vrutkovs/openshift-nginx:latest
        binary_path: /usr/share/nginx/html
        binary_image: quay.io/vrutkovs/blog:latest
    - name: login to quay
      run: docker login -u vrutkovs -p $DOCKER_PASSWORD quay.io
      env:
        DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      if: github.event_name == 'push'
    - name: push the image
      run: docker push quay.io/vrutkovs/blog:latest
      if: github.event_name == 'push'
